### ISSUE TITLE
Network never copied

### ISSUE THREAD

**Issue by jpmcrespo** [shakedzy/tic_tac_toe#1]
Hello,

I read what you wrote on medium and was studying your approach. I noticed this condition:
https://github.com/shakedzy/tic_tac_toe/blob/763bf3e53f1f1d3880969d6778212cfc96d4b058/players.py#L163
is never True, so you never ever copy the Q-Network to the Q-Target. I even tried to end it as soon as it was but it just never reached. 
![image](https://user-images.githubusercontent.com/17283046/54974412-d8ed7580-4f8b-11e9-9881-ba57d5d4d616.png)
I'm guessing instead of `self.memory.counter` you wanted to use `self.learn_counter` since they're just 1 unit apart anyway.

Am I missing something? If I'm right, I don't understand how the average reward can get better if the target never changes. 

Would you kindly review this and get back to me?

Thank you

**Comment by shakedzy** [comment]
Hi, thanks a lot - it seems you're correct. I just ran a sample using `self.learn_counter` as you suggested, and this seems to be the right thing to do. I'll push an updated version of the code and model hopefully today. Great job, thanks!

**Comment by shakedzy** [comment]
Pushed the changes and the new model. Thanks again! :)
